### PR TITLE
Added LinkedIn to header

### PR DESCRIPTION
**Pull request by joelbeckham**
Also made nbsp's consistent across all the icons available in the header.

### CODE REVIEW

**Comment by vjeantet** [comment]
+1 Thanks for this contribution

**Comment by vjeantet** [comment]
Hello @joelbeckham,  you removed the scroll down arrow from header and reduced the header size to a fixed height.
This change was committed  with a "Test..." commit log, is this voluntary

**Comment by joelbeckham** [comment]
Oops. I apologize. That wasn't suppose to get in there. Ill fix asap.

**Comment by joelbeckham** [comment]
I meant to only include 525efb6 (Added LinkedIn to header). Sorry about the extras! Looks like you've gotten those reverted, but just let me know if there's anything I can do to help clean up. Thanks for bringing an awesome theme to hugo.

**Comment by vjeantet** [comment]
No pb :) ang again, Thanks for this contribution

**Pull request merged**
